### ISSUE TITLE
Please add a configuration to make [Straw Cordage] be used for hanging raw meat up in the Smoke Rack

### ISSUE THREAD

**Issue by carlo-rigacci** [nuckable/TerraMisc#3]
Not for the line itself, the line could be made of sinew or other strings. But strings being consumed for hanging meat up on the Smoke Rack feels unrealistic. With [Straw Cordage] at least it becomes much more feasible in the early game.

**Comment by nuckable** [comment]
@Faintful I just checked the TFC+ code for this and while there technically are ways of implementing this feature, they're very work intensive and would break easily once the core code changes.

I sadly have to ask you to forward this feature request to TFC+
